# Generated by Django 4.2.3 on 2023-07-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_time", models.DateTimeField(auto_now=True)),
                ("deadline_time", models.DateTimeField()),
                ("is_done", models.BooleanField()),
                ("tags", models.ManyToManyField(related_name="tasks", to="tasks.tag")),
            ],
            options={
                "ordering": ["is_done", "-created_time"],
            },
        ),
    ]
