# Generated by Django 4.2.3 on 2023-07-22 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_created_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="tags",
            new_name="tag",
        ),
    ]
