# Generated by Django 4.2.3 on 2023-07-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_rename_tags_task_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="tag",
            new_name="tags",
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
